export const blogList = [
  {
    type: "update",
    id: 1,
    title: "How GPT works: ",
    category: "ai",
    subCategory: ["machine learning", "ui/ux", "Automation"],
    description:
      "ChatGPT is a language model developed by OpenAI. It is based on the GPT (Generative Pre-trained Transformer) architecture, specifically GPT-3.5. It is designed to generate human-like text responses to user prompts, making it useful for engaging in conversations, answering questions, providing information, and even assisting with various tasks. ChatGPT has been trained on a massive amount of data from the internet, allowing it to learn patterns, grammar, and context to generate coherent and contextually appropriate responses. It can understand and generate text in a wide range of topics, but it's important to note.",
    authorName: "Abhishek Kuntare",
    authorAvatar: "https://abhishekkuntare0210.vercel.app/images/abhi.jpg",
    createdAt: "June-17-2023",
    cover: "https://images.unsplash.com/photo-1684487747720-1ba29cda82f8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1332&q=80",
  },
 
  {
    type: "news",
    id: 2,
    title: "Frontend enginners ?",
    category: "development",
    subCategory: ["JavaScript", "React.js", "CSS"],
    description:
      "Frontend engineers are software engineers who specialize in building the user interface (UI) and user experience (UX) components of a website or application. They focus on the client-side development, which involves creating the visual and interactive elements that users interact with directly. The responsibilities of frontend engineers typically include: Web Development: Frontend engineers use web technologies such as HTML, CSS, and JavaScript to create and structure the UI of websites or web applications. They work with frameworks and libraries like React, Angular, or Vue.js to build interactive user interfaces. User Experience (UX): Frontend engineers collaborate with UX designers to ensure that the user interface is intuitive, visually appealing, and provides a smooth user experience. They implement UI designs and animations to enhance usability and user engagement.",
    authorName: "Abhishek Kuntare",
    authorAvatar: "https://abhishekkuntare0210.vercel.app/images/abhi.jpg",
    createdAt: "June 03, 2021",
    cover: "https://images.unsplash.com/photo-1569748130764-3fed0c102c59?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
  },
  {
    type: "jobs",
    id: 3,
    title: "[Framework] Vision framework",
    category: "development",
    subCategory: ["e-commerce store", "clothing", "shopping store"],
    description:
      "The Vision framework is a software framework provided by Apple for iOS, macOS, and other Apple platforms. It is part of the larger Core ML framework and provides a wide range of computer vision functionalities to developers. The Vision framework allows developers to incorporate computer vision capabilities into their applications, making it easier to perform tasks such as image analysis, face detection, object recognition, and more. Here are some key features and functionalities of the Vision framework: Image Analysis: The Vision framework provides powerful tools for analyzing images, including image alignment, barcode detection, text detection, and image saliency (identifying important regions in an image).",
    authorName: "Abhishek Kuntare",
    authorAvatar: "https://abhishekkuntare0210.vercel.app/images/abhi.jpg",
    createdAt: "June 03, 2021",
    cover: "https://images.unsplash.com/photo-1501621667575-af81f1f0bacc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
  },
  {
    type: "update",
    id: 4,
    title: "What is Metaverse ?",
    category: "latest",
    subCategory: ["adrenaline", "stay-fit", "lifestyle"],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: "Abhishek Kuntare",
    authorAvatar: "https://abhishekkuntare0210.vercel.app/images/abhi.jpg",
    createdAt: "June 03, 2021",
    cover: "https://plus.unsplash.com/premium_photo-1665203576234-593145303a87?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
  },
  {
    type: "jobs",
    id: 5,
    title: "New opening AI ?",
    category: "AI",
    subCategory: ["AI", "Automation", "tech"],
    description:
      "AI, short for Artificial Intelligence, refers to the development of computer systems that can perform tasks that typically require human intelligence. It involves creating algorithms and models that enable machines to exhibit intelligent behavior, learn from data, adapt to new situations, and make decisions or perform tasks autonomously. AI can be categorized into two main types: Narrow AI (also known as Weak AI): Narrow AI refers to AI systems designed to perform specific tasks within a limited domain. Examples include voice assistants like Siri or Alexa, image recognition systems, and recommendation algorithms. These systems excel in their designated tasks but lack general intelligence..",
    authorName: "Abhishek Kuntare",
    authorAvatar: "https://abhishekkuntare0210.vercel.app/images/abhi.jpg",
    createdAt: "June 03, 2021",
    cover: "https://plus.unsplash.com/premium_photo-1681297399245-9b272f07f119?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1332&q=80",
  },
  {
    type: "update",
    id: 6,
    title: "Another hack of DARK WEB ?",
    category: "latest",
    subCategory: ["HACK", "DARK", "MAlWARE"],
    description:
      "The dark web refers to a part of the internet that is not indexed by search engines and requires special software, configurations, or authorization to access. It is a subset of the deep web, which includes all web pages that are not indexed by search engines. The dark web is known for hosting websites and online communities that operate anonymously and often involve illegal activities. These activities can include the sale of drugs, weapons, stolen data, hacking tools, counterfeit goods, and various other illicit services. It also provides a platform for activities such as cybercrime,.",
    authorName: "Abhishek Kuntare",
    authorAvatar: "https://abhishekkuntare0210.vercel.app/images/abhi.jpg",
    createdAt: "June 03, 2021",
    cover:
      "https://images.unsplash.com/photo-1611172061501-ee8ef02d49c5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=821&q=80",
  },
  {
    type: "jobs",
    id: 7,
    title: "Google layoffs",
    category: "latest",
    subCategory: ["layoffs", "Google", "EMP"],
    description:
      "However, it's worth noting that like any company, Google has undergone organizational changes and restructuring throughout its history, which have occasionally included layoffs. Layoffs can occur for various reasons, such as strategic shifts, cost-cutting measures, or changes in market conditions. For up-to-date information on Google's current situation or any recent layoffs, I recommend checking reliable news sources, Google's official announcements, or other reputable resources.",
    authorName: "Abhishek Kuntare",
    authorAvatar: "https://abhishekkuntare0210.vercel.app/images/abhi.jpg",
    createdAt: "June 03, 2021",
    cover: "https://images.unsplash.com/photo-1529612700005-e35377bf1415?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
  },
  {
    type: "news",
    id: 8,
    title: "Bard new Feature ?",
    category: "latest",
    subCategory: ["bard", "google", "ai"],
    description:
      "The term bard historically refers to a poet, storyteller, or musician who composes and performs epic or lyrical works. The concept of a bard originates from ancient Celtic and Gaelic cultures, where bards held a respected role in society, often serving as oral historians, praise singers, and entertainers. Bards were skilled in various forms of artistic expression, including poetry, song, and storytelling. They played a crucial role in preserving and transmitting cultural and historical knowledge through their performances. Bards were highly regarded for their ability to captivate audiences with their words, often accompanied by musical instruments.",
    authorAvatar: "https://abhishekkuntare0210.vercel.app/images/abhi.jpg",
    createdAt: "June 03, 2021",
    cover: "https://images.unsplash.com/photo-1679958157899-069a60dc6a3d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1181&q=80",
  },
  {
    type: "update",
    id: 9,
    title: "New Technology ?",
    category: "latest",
    subCategory: ["tech", "ai", "new"],
    description:
      "As an AI language model, my responses are based on information available up until September 2021, and I don't have access to real-time news updates. Therefore, I cannot provide specific updates on the latest news in the tech industry. To stay updated with the latest news in the tech industry, I recommend checking reputable technology news websites, such as TechCrunch, The Verge, CNET, Engadget, or visiting the technology section of established news outlets like Reuters or BBC News. These sources can provide you with the most current information on advancements, product releases, company news, and other relevant topics in the world of technology..",
    authorAvatar: "https://abhishekkuntare0210.vercel.app/images/abhi.jpg",
    createdAt: "June 03, 2021",
    cover: "https://images.unsplash.com/photo-1516251193007-45ef944ab0c6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
  },
  {
    type: "news",
    id: 10,
    title: "Why layoffs ?",
    category: "latest",
    subCategory: ["emoplyee", "job", "fired"],
    description:
      "Layoffs can occur for several reasons, and each company's situation may be unique. Here are a few common reasons why companies, including Google, may resort to layoffs: Business restructuring: Companies may undergo reorganizations or strategic shifts to adapt to changing market conditions, technological advancements, or shifts in customer demand. Layoffs may be a result of eliminating redundancies, streamlining operations, or reallocating resources to focus on core business areas.",
    authorAvatar: "https://abhishekkuntare0210.vercel.app/images/abhi.jpg",
    createdAt: "June 03, 2021",
    cover: "https://images.unsplash.com/photo-1529400971008-f566de0e6dfc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
  },
];
